apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opencv-server-data
  labels:
    app: opencv-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
