apiVersion: v1
kind: Service
metadata:
  name: opencv-server
  labels:
    app: opencv-server
spec:
  type: NodePort
  selector:
    app: opencv-server
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
